import { relations } from "drizzle-orm";
import { mysqlTable, varchar, text, timestamp, boolean, int, index } from "drizzle-orm/mysql-core";

// --- CATEGORIES ---
export const categories = mysqlTable("categories", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 100 }).notNull().unique(),
  slug: varchar("slug", { length: 100 }).notNull().unique(),
  description: varchar("description", { length: 255 }),
  createdAt: timestamp("created_at").defaultNow(),
});

// --- POSTS ---
export const posts = mysqlTable("posts", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  excerpt: varchar("excerpt", { length: 500 }),
  content: text("content").notNull(),
  categoryOld: varchar("category_old", { length: 100 }).default("LIFE"), // Umbenannt wegen Konflikt
  categoryId: int("category_id").references(() => categories.id, { onDelete: "set null" }),
  coverImage: varchar("cover_image", { length: 500 }),
  
  // SEO & Meta
  metaTitle: varchar("meta_title", { length: 255 }),
  metaDescription: varchar("meta_description", { length: 500 }),
  keywords: varchar("keywords", { length: 500 }), // Kommagetrennte Liste
  ogImage: varchar("og_image", { length: 500 }),
  
  readTime: int("read_time"),
  published: boolean("published").default(false),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow(),
});


// --- AUTH SCHEMA (GENERATED BY BETTER-AUTH) ---
export const users = mysqlTable("users", {
  id: varchar("id", { length: 36 }).primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { fsp: 3 })
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  twoFactorEnabled: boolean("two_factor_enabled").default(false),
});

export const sessions = mysqlTable(
  "sessions",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    expiresAt: timestamp("expires_at", { fsp: 3 }).notNull(),
    token: varchar("token", { length: 255 }).notNull().unique(),
    createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { fsp: 3 })
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: varchar("user_id", { length: 36 })
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
  },
  (table) => [index("sessions_userId_idx").on(table.userId)],
);

export const accounts = mysqlTable(
  "accounts",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: varchar("user_id", { length: 36 })
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { fsp: 3 }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { fsp: 3 }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { fsp: 3 })
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("accounts_userId_idx").on(table.userId)],
);

export const verifications = mysqlTable(
  "verifications",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    identifier: varchar("identifier", { length: 255 }).notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { fsp: 3 }).notNull(),
    createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { fsp: 3 })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verifications_identifier_idx").on(table.identifier)],
);

export const twoFactors = mysqlTable(
  "two_factors",
  {
    id: varchar("id", { length: 36 }).primaryKey(),
    secret: varchar("secret", { length: 255 }).notNull(),
    backupCodes: text("backup_codes").notNull(),
    userId: varchar("user_id", { length: 36 })
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    verified: boolean("verified").default(true),
  },
  (table) => [
    index("twoFactors_secret_idx").on(table.secret),
    index("twoFactors_userId_idx").on(table.userId),
  ],
);

// --- LOVANARIS SUBMISSIONS ---
export const lovanarisSubmissions = mysqlTable("lovanaris_submissions", {
  id: int("id").autoincrement().primaryKey(),
  code: varchar("code", { length: 20 }).notNull().unique(),
  story: text("story").notNull(),
  category: varchar("category", { length: 255 }).notNull(),
  status: varchar("status", { length: 50 }).default("pending").notNull(), // pending, approved, rejected, info_needed
  adminMessage: text("admin_message"),
  userReply: text("user_reply"),
  lockedBy: int("locked_by"), // ID des Admins, der gerade bearbeitet
  lockedAt: timestamp("locked_at"),
  processedBy: int("processed_by"), // Letzter Bearbeiter
  securityToken: varchar("security_token", { length: 100 }), // Für Löschanträge
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow(),
});

// --- LOVANARIS CONTACT REQUESTS ---
export const lovanarisContactRequests = mysqlTable("lovanaris_contact_requests", {
  id: int("id").autoincrement().primaryKey(),
  type: varchar("type", { length: 50 }).notNull(), // 'deletion', 'general'
  email: varchar("email", { length: 255 }), // Nur bei 'general'
  storyCode: varchar("story_code", { length: 20 }), // Nur bei 'deletion'
  securityToken: varchar("security_token", { length: 100 }), // Nur bei 'deletion'
  validationNote: text("validation_note"), // Für Altfälle oder zusätzliche Infos
  message: text("message").notNull(),
  status: varchar("status", { length: 50 }).default("pending").notNull(), // pending, processed, archived
  createdAt: timestamp("created_at").defaultNow(),
});

// --- RELATIONS ---
export const categoriesRelations = relations(categories, ({ many }) => ({
  posts: many(posts),
}));

export const postsRelations = relations(posts, ({ one }) => ({
  category: one(categories, {
    fields: [posts.categoryId],
    references: [categories.id],
  }),
}));

export const usersRelations = relations(users, ({ many }) => ({
  sessions: many(sessions),
  accounts: many(accounts),
  twoFactors: many(twoFactors),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  users: one(users, {
    fields: [sessions.userId],
    references: [users.id],
  }),
}));

export const accountsRelations = relations(accounts, ({ one }) => ({
  users: one(users, {
    fields: [accounts.userId],
    references: [users.id],
  }),
}));

export const twoFactorsRelations = relations(twoFactors, ({ one }) => ({
  users: one(users, {
    fields: [twoFactors.userId],
    references: [users.id],
  }),
}));

export const lovanarisRateLimits = mysqlTable("lovanaris_rate_limits", {
  id: int("id").autoincrement().primaryKey(),
  identifier: varchar("identifier", { length: 255 }).notNull(),
  actionType: varchar("action_type", { length: 50 }).notNull(),
  attempts: int("attempts").default(0),
  lastAttempt: timestamp("last_attempt").defaultNow().onUpdateNow(),
  blockedUntil: timestamp("blocked_until"),
});

export const lovanarisAdmins = mysqlTable("lovanaris_admins", {
  id: int("id").autoincrement().primaryKey(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  password: varchar("password", { length: 255 }).notNull(), // Hashed
  name: varchar("name", { length: 255 }),
  role: varchar("role", { length: 20 }).default("moderator").notNull(), // super_admin, moderator
  createdAt: timestamp("created_at").defaultNow(),
});

export const lovanarisSessions = mysqlTable("lovanaris_sessions", {
  id: int("id").autoincrement().primaryKey(),
  adminId: int("admin_id").notNull(),
  token: varchar("token", { length: 255 }).notNull().unique(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

// Lovanaris Chat Messages (Anonymized History)
export const lovanarisMessages = mysqlTable("lovanaris_messages", {
  id: int("id").autoincrement().primaryKey(),
  submissionId: int("submission_id").notNull(),
  adminId: int("admin_id"), // Wer hat die Nachricht gesendet?
  role: varchar("role", { length: 20 }).notNull(), // 'admin' or 'user'
  content: text("content").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});
